package com.pt.entity;

public class MyCategories {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_categories.id
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_categories.name
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_categories.id
	 * @return  the value of my_categories.id
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_categories.id
	 * @param id  the value for my_categories.id
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_categories.name
	 * @return  the value of my_categories.name
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_categories.name
	 * @param name  the value for my_categories.name
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}
}