package com.pt.entity;

import java.util.Date;

public class MyComment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_comment.id
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_comment.blog_id
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	private Long blogId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_comment.content
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_comment.user_id
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_comment.user_email
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	private String userEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_comment.user_name
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_comment.add_time
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_comment.reply_state
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	private Integer replyState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_comment.reply_content
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	private String replyContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_comment.reply_time
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	private Date replyTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_comment.id
	 * @return  the value of my_comment.id
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_comment.id
	 * @param id  the value for my_comment.id
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_comment.blog_id
	 * @return  the value of my_comment.blog_id
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public Long getBlogId() {
		return blogId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_comment.blog_id
	 * @param blogId  the value for my_comment.blog_id
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public void setBlogId(Long blogId) {
		this.blogId = blogId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_comment.content
	 * @return  the value of my_comment.content
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_comment.content
	 * @param content  the value for my_comment.content
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_comment.user_id
	 * @return  the value of my_comment.user_id
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_comment.user_id
	 * @param userId  the value for my_comment.user_id
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_comment.user_email
	 * @return  the value of my_comment.user_email
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public String getUserEmail() {
		return userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_comment.user_email
	 * @param userEmail  the value for my_comment.user_email
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail == null ? null : userEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_comment.user_name
	 * @return  the value of my_comment.user_name
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_comment.user_name
	 * @param userName  the value for my_comment.user_name
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_comment.add_time
	 * @return  the value of my_comment.add_time
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_comment.add_time
	 * @param addTime  the value for my_comment.add_time
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_comment.reply_state
	 * @return  the value of my_comment.reply_state
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public Integer getReplyState() {
		return replyState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_comment.reply_state
	 * @param replyState  the value for my_comment.reply_state
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public void setReplyState(Integer replyState) {
		this.replyState = replyState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_comment.reply_content
	 * @return  the value of my_comment.reply_content
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public String getReplyContent() {
		return replyContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_comment.reply_content
	 * @param replyContent  the value for my_comment.reply_content
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent == null ? null : replyContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_comment.reply_time
	 * @return  the value of my_comment.reply_time
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public Date getReplyTime() {
		return replyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_comment.reply_time
	 * @param replyTime  the value for my_comment.reply_time
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	public void setReplyTime(Date replyTime) {
		this.replyTime = replyTime;
	}
}