package com.pt.entity;

public class MyExp {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_exp.id
	 * @mbggenerated  Mon May 23 11:46:26 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_exp.title
	 * @mbggenerated  Mon May 23 11:46:26 CST 2016
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_exp.content
	 * @mbggenerated  Mon May 23 11:46:26 CST 2016
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_exp.year
	 * @mbggenerated  Mon May 23 11:46:26 CST 2016
	 */
	private String year;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_exp.mmdd
	 * @mbggenerated  Mon May 23 11:46:26 CST 2016
	 */
	private String mmdd;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_exp.id
	 * @return  the value of my_exp.id
	 * @mbggenerated  Mon May 23 11:46:26 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_exp.id
	 * @param id  the value for my_exp.id
	 * @mbggenerated  Mon May 23 11:46:26 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_exp.title
	 * @return  the value of my_exp.title
	 * @mbggenerated  Mon May 23 11:46:26 CST 2016
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_exp.title
	 * @param title  the value for my_exp.title
	 * @mbggenerated  Mon May 23 11:46:26 CST 2016
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_exp.content
	 * @return  the value of my_exp.content
	 * @mbggenerated  Mon May 23 11:46:26 CST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_exp.content
	 * @param content  the value for my_exp.content
	 * @mbggenerated  Mon May 23 11:46:26 CST 2016
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_exp.year
	 * @return  the value of my_exp.year
	 * @mbggenerated  Mon May 23 11:46:26 CST 2016
	 */
	public String getYear() {
		return year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_exp.year
	 * @param year  the value for my_exp.year
	 * @mbggenerated  Mon May 23 11:46:26 CST 2016
	 */
	public void setYear(String year) {
		this.year = year == null ? null : year.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_exp.mmdd
	 * @return  the value of my_exp.mmdd
	 * @mbggenerated  Mon May 23 11:46:26 CST 2016
	 */
	public String getMmdd() {
		return mmdd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_exp.mmdd
	 * @param mmdd  the value for my_exp.mmdd
	 * @mbggenerated  Mon May 23 11:46:26 CST 2016
	 */
	public void setMmdd(String mmdd) {
		this.mmdd = mmdd == null ? null : mmdd.trim();
	}
}