package com.pt.entity;

import java.util.Date;

public class MyMsg {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_msg.id
	 * @mbggenerated  Mon May 16 16:32:39 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_msg.email
	 * @mbggenerated  Mon May 16 16:32:39 CST 2016
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_msg.name
	 * @mbggenerated  Mon May 16 16:32:39 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_msg.title
	 * @mbggenerated  Mon May 16 16:32:39 CST 2016
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_msg.content
	 * @mbggenerated  Mon May 16 16:32:39 CST 2016
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_msg.state
	 * @mbggenerated  Mon May 16 16:32:39 CST 2016
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column my_msg.add_time
	 * @mbggenerated  Mon May 16 16:32:39 CST 2016
	 */
	private Date addTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_msg.id
	 * @return  the value of my_msg.id
	 * @mbggenerated  Mon May 16 16:32:39 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_msg.id
	 * @param id  the value for my_msg.id
	 * @mbggenerated  Mon May 16 16:32:39 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_msg.email
	 * @return  the value of my_msg.email
	 * @mbggenerated  Mon May 16 16:32:39 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_msg.email
	 * @param email  the value for my_msg.email
	 * @mbggenerated  Mon May 16 16:32:39 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_msg.name
	 * @return  the value of my_msg.name
	 * @mbggenerated  Mon May 16 16:32:39 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_msg.name
	 * @param name  the value for my_msg.name
	 * @mbggenerated  Mon May 16 16:32:39 CST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_msg.title
	 * @return  the value of my_msg.title
	 * @mbggenerated  Mon May 16 16:32:39 CST 2016
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_msg.title
	 * @param title  the value for my_msg.title
	 * @mbggenerated  Mon May 16 16:32:39 CST 2016
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_msg.content
	 * @return  the value of my_msg.content
	 * @mbggenerated  Mon May 16 16:32:39 CST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_msg.content
	 * @param content  the value for my_msg.content
	 * @mbggenerated  Mon May 16 16:32:39 CST 2016
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_msg.state
	 * @return  the value of my_msg.state
	 * @mbggenerated  Mon May 16 16:32:39 CST 2016
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_msg.state
	 * @param state  the value for my_msg.state
	 * @mbggenerated  Mon May 16 16:32:39 CST 2016
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column my_msg.add_time
	 * @return  the value of my_msg.add_time
	 * @mbggenerated  Mon May 16 16:32:39 CST 2016
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column my_msg.add_time
	 * @param addTime  the value for my_msg.add_time
	 * @mbggenerated  Mon May 16 16:32:39 CST 2016
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}
}