package com.pt.entity;

import java.util.Date;

public class TruthOrDareForUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column truth_or_dare_for_user.id
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column truth_or_dare_for_user.user_id
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column truth_or_dare_for_user.type
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column truth_or_dare_for_user.content
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column truth_or_dare_for_user.weight
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	private Integer weight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column truth_or_dare_for_user.state
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column truth_or_dare_for_user.add_time
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column truth_or_dare_for_user.upt_time
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	private Date uptTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column truth_or_dare_for_user.id
	 * @return  the value of truth_or_dare_for_user.id
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column truth_or_dare_for_user.id
	 * @param id  the value for truth_or_dare_for_user.id
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column truth_or_dare_for_user.user_id
	 * @return  the value of truth_or_dare_for_user.user_id
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column truth_or_dare_for_user.user_id
	 * @param userId  the value for truth_or_dare_for_user.user_id
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column truth_or_dare_for_user.type
	 * @return  the value of truth_or_dare_for_user.type
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column truth_or_dare_for_user.type
	 * @param type  the value for truth_or_dare_for_user.type
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column truth_or_dare_for_user.content
	 * @return  the value of truth_or_dare_for_user.content
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column truth_or_dare_for_user.content
	 * @param content  the value for truth_or_dare_for_user.content
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column truth_or_dare_for_user.weight
	 * @return  the value of truth_or_dare_for_user.weight
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	public Integer getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column truth_or_dare_for_user.weight
	 * @param weight  the value for truth_or_dare_for_user.weight
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column truth_or_dare_for_user.state
	 * @return  the value of truth_or_dare_for_user.state
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column truth_or_dare_for_user.state
	 * @param state  the value for truth_or_dare_for_user.state
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column truth_or_dare_for_user.add_time
	 * @return  the value of truth_or_dare_for_user.add_time
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column truth_or_dare_for_user.add_time
	 * @param addTime  the value for truth_or_dare_for_user.add_time
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column truth_or_dare_for_user.upt_time
	 * @return  the value of truth_or_dare_for_user.upt_time
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	public Date getUptTime() {
		return uptTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column truth_or_dare_for_user.upt_time
	 * @param uptTime  the value for truth_or_dare_for_user.upt_time
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	public void setUptTime(Date uptTime) {
		this.uptTime = uptTime;
	}
}