package com.pt.dao;

import java.util.HashMap;
import java.util.List;

import com.pt.entity.MyBlog;
import com.pt.entity.TruthOrDare;

public interface MyBlogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_blog
	 * @mbggenerated  Sat May 07 14:44:09 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_blog
	 * @mbggenerated  Sat May 07 14:44:09 CST 2016
	 */
	int insert(MyBlog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_blog
	 * @mbggenerated  Sat May 07 14:44:09 CST 2016
	 */
	int insertSelective(MyBlog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_blog
	 * @mbggenerated  Sat May 07 14:44:09 CST 2016
	 */
	MyBlog selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_blog
	 * @mbggenerated  Sat May 07 14:44:09 CST 2016
	 */
	int updateByPrimaryKeySelective(MyBlog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_blog
	 * @mbggenerated  Sat May 07 14:44:09 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(MyBlog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_blog
	 * @mbggenerated  Sat May 07 14:44:09 CST 2016
	 */
	int updateByPrimaryKey(MyBlog record);
	
	
	List<MyBlog> getMyBlogLst(HashMap map);

	List<MyBlog> getMyBlogAllLst();
}