package com.pt.dao;

import com.pt.entity.MyCategories;

public interface MyCategoriesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_categories
	 * @mbggenerated  Sat May 07 14:44:09 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_categories
	 * @mbggenerated  Sat May 07 14:44:09 CST 2016
	 */
	int insert(MyCategories record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_categories
	 * @mbggenerated  Sat May 07 14:44:09 CST 2016
	 */
	int insertSelective(MyCategories record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_categories
	 * @mbggenerated  Sat May 07 14:44:09 CST 2016
	 */
	MyCategories selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_categories
	 * @mbggenerated  Sat May 07 14:44:09 CST 2016
	 */
	int updateByPrimaryKeySelective(MyCategories record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_categories
	 * @mbggenerated  Sat May 07 14:44:09 CST 2016
	 */
	int updateByPrimaryKey(MyCategories record);
}