package com.pt.dao;

import java.util.List;

import com.pt.entity.MyCategories;

public interface MyCategoriesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_categories
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_categories
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	int insert(MyCategories record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_categories
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	int insertSelective(MyCategories record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_categories
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	MyCategories selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_categories
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	int updateByPrimaryKeySelective(MyCategories record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_categories
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	int updateByPrimaryKey(MyCategories record);

	List<MyCategories> getCategoriesAllList();
}