package com.pt.dao;

import java.util.HashMap;
import java.util.List;

import com.pt.entity.MyComment;

public interface MyCommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_comment
	 * @mbggenerated  Mon May 23 11:46:26 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_comment
	 * @mbggenerated  Mon May 23 11:46:26 CST 2016
	 */
	int insert(MyComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_comment
	 * @mbggenerated  Mon May 23 11:46:26 CST 2016
	 */
	int insertSelective(MyComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_comment
	 * @mbggenerated  Mon May 23 11:46:26 CST 2016
	 */
	MyComment selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_comment
	 * @mbggenerated  Mon May 23 11:46:26 CST 2016
	 */
	int updateByPrimaryKeySelective(MyComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_comment
	 * @mbggenerated  Mon May 23 11:46:26 CST 2016
	 */
	int updateByPrimaryKey(MyComment record);

	List<MyComment> selectAllByBlogId(Long id);
	
	List<MyComment> selectByBlogId(HashMap map);
}