package com.pt.dao;

import com.pt.entity.MyComment;

public interface MyCommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_comment
	 * @mbggenerated  Sun May 08 16:35:30 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_comment
	 * @mbggenerated  Sun May 08 16:35:30 CST 2016
	 */
	int insert(MyComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_comment
	 * @mbggenerated  Sun May 08 16:35:30 CST 2016
	 */
	int insertSelective(MyComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_comment
	 * @mbggenerated  Sun May 08 16:35:30 CST 2016
	 */
	MyComment selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_comment
	 * @mbggenerated  Sun May 08 16:35:30 CST 2016
	 */
	int updateByPrimaryKeySelective(MyComment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_comment
	 * @mbggenerated  Sun May 08 16:35:30 CST 2016
	 */
	int updateByPrimaryKey(MyComment record);
}