package com.pt.dao;

import java.util.List;

import com.pt.entity.MyExp;

public interface MyExpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_exp
     *
     * @mbggenerated Mon May 16 16:32:39 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_exp
     *
     * @mbggenerated Mon May 16 16:32:39 CST 2016
     */
    int insert(MyExp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_exp
     *
     * @mbggenerated Mon May 16 16:32:39 CST 2016
     */
    int insertSelective(MyExp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_exp
     *
     * @mbggenerated Mon May 16 16:32:39 CST 2016
     */
    MyExp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_exp
     *
     * @mbggenerated Mon May 16 16:32:39 CST 2016
     */
    int updateByPrimaryKeySelective(MyExp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_exp
     *
     * @mbggenerated Mon May 16 16:32:39 CST 2016
     */
    int updateByPrimaryKey(MyExp record);
    
    List<MyExp> selectAll();
}