package com.pt.dao;

import com.pt.entity.MyMsg;

public interface MyMsgMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_msg
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_msg
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	int insert(MyMsg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_msg
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	int insertSelective(MyMsg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_msg
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	MyMsg selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_msg
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	int updateByPrimaryKeySelective(MyMsg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_msg
	 * @mbggenerated  Fri May 13 15:25:39 CST 2016
	 */
	int updateByPrimaryKey(MyMsg record);
}