package com.pt.dao;

import java.util.HashMap;
import java.util.List;

import com.pt.entity.MyMsg;

public interface MyMsgMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_msg
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_msg
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	int insert(MyMsg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_msg
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	int insertSelective(MyMsg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_msg
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	MyMsg selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_msg
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	int updateByPrimaryKeySelective(MyMsg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table my_msg
	 * @mbggenerated  Mon May 16 11:24:18 CST 2016
	 */
	int updateByPrimaryKey(MyMsg record);

	List<MyMsg> getMsgList(HashMap<String, Object> map);
}