package com.pt.dao;

import com.pt.entity.MyPhoto;

public interface MyPhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_photo
     *
     * @mbggenerated Sun May 08 16:35:30 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_photo
     *
     * @mbggenerated Sun May 08 16:35:30 CST 2016
     */
    int insert(MyPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_photo
     *
     * @mbggenerated Sun May 08 16:35:30 CST 2016
     */
    int insertSelective(MyPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_photo
     *
     * @mbggenerated Sun May 08 16:35:30 CST 2016
     */
    MyPhoto selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_photo
     *
     * @mbggenerated Sun May 08 16:35:30 CST 2016
     */
    int updateByPrimaryKeySelective(MyPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_photo
     *
     * @mbggenerated Sun May 08 16:35:30 CST 2016
     */
    int updateByPrimaryKey(MyPhoto record);
}