package com.pt.dao;

import com.pt.entity.TruthOrDareForUser;

public interface TruthOrDareForUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table truth_or_dare_for_user
	 * @mbggenerated  Sun May 08 16:35:30 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table truth_or_dare_for_user
	 * @mbggenerated  Sun May 08 16:35:30 CST 2016
	 */
	int insert(TruthOrDareForUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table truth_or_dare_for_user
	 * @mbggenerated  Sun May 08 16:35:30 CST 2016
	 */
	int insertSelective(TruthOrDareForUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table truth_or_dare_for_user
	 * @mbggenerated  Sun May 08 16:35:30 CST 2016
	 */
	TruthOrDareForUser selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table truth_or_dare_for_user
	 * @mbggenerated  Sun May 08 16:35:30 CST 2016
	 */
	int updateByPrimaryKeySelective(TruthOrDareForUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table truth_or_dare_for_user
	 * @mbggenerated  Sun May 08 16:35:30 CST 2016
	 */
	int updateByPrimaryKey(TruthOrDareForUser record);
}