package com.pt.dao;

import java.util.HashMap;
import java.util.List;

import com.pt.entity.TruthOrDare;

public interface TruthOrDareMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table truth_or_dare
	 * @mbggenerated  Wed May 11 12:19:34 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table truth_or_dare
	 * @mbggenerated  Wed May 11 12:19:34 CST 2016
	 */
	int insert(TruthOrDare record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table truth_or_dare
	 * @mbggenerated  Wed May 11 12:19:34 CST 2016
	 */
	int insertSelective(TruthOrDare record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table truth_or_dare
	 * @mbggenerated  Wed May 11 12:19:34 CST 2016
	 */
	TruthOrDare selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table truth_or_dare
	 * @mbggenerated  Wed May 11 12:19:34 CST 2016
	 */
	int updateByPrimaryKeySelective(TruthOrDare record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table truth_or_dare
	 * @mbggenerated  Wed May 11 12:19:34 CST 2016
	 */
	int updateByPrimaryKey(TruthOrDare record);

	List<TruthOrDare> getTruthOrDareLst(HashMap map);
	
	List<TruthOrDare> getTruthOrDareAllLst();
}